### ISSUE TITLE
enabling modules for future builds

### ISSUE THREAD

**Issue by Maeslin** [libre-computer-project/libretech-linux#12]
Would it be possible to include the following kernel modules for future builds? Current built kernel available on the Libre Computer repository is 5.19.8-03347-g542d481c2a42, kernel version currently available on github is 5.19.6 and these modules are not active in the current configuration.
 
- /pps/clients/pps-gpio
   (CONFIG_PPS_CLIENT_GPIO=m)
- /tty/serial/sc16is7xx  (both i2c and spi modes enabled)
   (CONFIG_SERIAL_SC16IS7XX_CORE=m)
   (CONFIG_SERIAL_SC16IS7XX=m)
   (CONFIG_SERIAL_SC16IS7XX_I2C=y)
   (CONFIG_SERIAL_SC16IS7XX_SPI=y)

**Comment by dsx724** [comment]
Added to 5.19.8-03349
