### ISSUE TITLE
Support for Linux 6.2?

### ISSUE THREAD

**Issue by kerta1n** [libre-computer-project/libretech-linux#15]
Hello, I know that this is a newly released version of the kernel, but will there be a new update soon? Thanks to the devs for all their hard work

**Comment by dsx724** [comment]
The plan is to stick to Linux 6.1 for stable and attach unstable to rolling mainline. Linux 6.1 is undergoing extensive validation right now and will be pushed soon to stable.

**Comment by dsx724** [comment]
We only have the engineering bandwidth to maintain LTS releases. We will offer vanilla releases soon but they lack the full capabilities of our LTS kernel. We should have automated builds of every stable release by the end of May.
