### ISSUE TITLE
Hardware acceleration for ROC-RK3399-PC (Renegade Elite)

### ISSUE THREAD

**Issue by tobeorla** [libre-computer-project/libretech-linux#2]
There are no Mali T8XX userspace drivers for linux and Panfrost (https://gitlab.freedesktop.org/panfrost/) is still a work-in-progress alternative.
¿Does it mean that Renegade won't have hardware acceleration?

**Comment by superna9999** [comment]
Rockchip provides everything you need here https://github.com/rockchip-linux/libmali/tree/29mirror/lib/aarch64-linux-gnu

**Comment by dsx724** [comment]
This branch is not currently optimized for the RK3399. You currently need to load the mali userspace blob and have the mali kernel driver for best performance. We plan to switch wholesale to panfrost on the next Linux LTS (5.10+) and use Mesa userspace.
