### ISSUE TITLE
Add XT_SET to kernel module

### ISSUE THREAD

**Issue by dretechtips** [libre-computer-project/libretech-linux#20]
Hello,

I'm using some VPN software that requires access to the xt_set kernel module. This module is built into the Raspberry PI OS kernel (6.6.20+rpt-rpi-2712), but not in the LibreTech Linux kernel. Please include this kernel module in the future release build of the kernel. 

Kernel Version: LibreTech Linux 6.1.64-11810-g69b1ffe8ef6c

Thank you,

**Comment by dsx724** [comment]
You need to update your kernel to the latest. This is already set.
