### ISSUE TITLE
linux 4.19.3+: h5: fullscreen gles on X doesn't update screen, spams logs

### ISSUE THREAD

**Issue by 3b** [libre-computer-project/libretech-linux#3]
When running `glmark2-es2 --fullscreen` without a compositor (I tested with bare X + an xterm, but pretty sure just disabling compositor with xfce had same problem when I tried in the past), it only displays the first frame and never updates afterwards. `/var/log/Xorg.0.log`  gets

```
[ 16612.736] (WW) ARMSOC(0): flip queue failed: Invalid argument
[ 16612.736] (EE) ARMSOC(0): ERROR: swap 72821 ARMSOC_SWAP_FAIL on swap complete
[ 16612.736] (EE) ARMSOC(0): [DRI2] DRI2SwapBuffers: driver failed to schedule swap
[ 16612.740] (WW) ARMSOC(0): flip queue failed: Invalid argument
[ 16612.740] (EE) ARMSOC(0): ERROR: swap 72822 ARMSOC_SWAP_FAIL on swap complete
[ 16612.740] (EE) ARMSOC(0): [DRI2] DRI2SwapBuffers: driver failed to schedule swap
```

Performance reported by `glmark2-es2` is reasonable (~380fps for first test), and load reported by `top` is also reasonable (`glmark2-es2` at ~70%, `Xorg` at ~30%).

Without fullscreen, or with compositor, it displays properly, but runs slowly. ~56fs with `Xorg` at 95% and `glmark2-es2` at ~5% or less.

With `glmark2-es2-drm` (from git, since ubuntu version doesn't find the gpu), it runs at consistent 65fps (which sounds reasonable for this display), with low load (~5%).

tested with Ubuntu 18.04/bionic xfce 2019-03-25 image, after apt update/upgrade, `glmark2-es2` from apt

**Comment by dsx724** [comment]
X11 is slow because it has to copy the data during compositing on a device that is very memory bandwidth limited. Even on Wayland might need some zero-copy optimizations.

**Comment by 3b** [comment]
Right, "slow compositing" is annoying but understandable. This bug is about it not working at all, when fullscreen with compositing disabled. I assume that it does have some generic zero-copy optimization in that case, it just doesn't work. The extra info about being slower with compositing was just for comparison to support that assumption.
