### ISSUE TITLE
Missing upstream Git tags

### ISSUE THREAD

**Issue by woodsts** [libre-computer-project/libretech-linux#4]
After cloning the 'v5.4/libretech-master-stable-build' branch, I noticed that the tags stopped around version 4.14. The tags should be fetched from upstream linux and pushed here for consistency.

**Comment by dsx724** [comment]
@woodsts The previous trees were messy because of a lot of out-of-tree stuff. This has all been merged upstream and now we require minimal out-of-tree patches. We will start tracking LTS releases starting at the end of this year as we reach feature complete on all of our boards.
